# Import Relevant libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns


# Load the dataset

In [2]:
fd=pd.read_excel('fifa21 raw data v2.xlsx')
fd.head()

ID               Name                      LongName  \
0  158023           L. Messi                  Lionel Messi   
1   20801  Cristiano Ronaldo  C. Ronaldo dos Santos Aveiro   
2  200389           J. Oblak                     Jan Oblak   
3  192985       K. De Bruyne               Kevin De Bruyne   
4  190871          Neymar Jr    Neymar da Silva Santos Jr.   

                                           photoUrl  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   
1  https://cdn.sofifa.com/players/020/801/21_60.png   
2  https://cdn.sofifa.com/players/200/389/21_60.png   
3  https://cdn.sofifa.com/players/192/985/21_60.png   
4  https://cdn.sofifa.com/players/190/871/21_60.png   

                                           playerUrl Nationality  Age  ↓OVA  \
0  http://sofifa.com/player/158023/lionel-messi/2...   Argentina   33    93   
1  http://sofifa.com/player/20801/c-ronaldo-dos-s...    Portugal   35    92   
2  http://sofifa.com/player/200389/jan-oblak/210006/    Slovenia   27    91   
3  http://sofifa.com/player/192985/kevin-de-bruyn...     Belgium   29    91   
4  http://sofifa.com/player/190871/neymar-da-silv...      Brazil   28    91   

   POT                         Club  ...     A/W     D/W   IR PAC SHO  PAS  \
0   93         \n\n\n\nFC Barcelona  ...  Medium     Low  5 ★  85  92   91   
1   92             \n\n\n\nJuventus  ...    High     Low  5 ★  89  93   81   
2   93      \n\n\n\nAtlético Madrid  ...  Medium  Medium  3 ★  87  92   78   
3   91      \n\n\n\nManchester City  ...    High    High  4 ★  76  86   93   
4   91  \n\n\n\nParis Saint-Germain  ...    High  Medium  5 ★  91  85   86   

  DRI DEF PHY Hits  
0  95  38  65  771  
1  89  35  77  562  
2  90  52  90  150  
3  88  64  78  207  
4  94  36  59  595  

[5 rows x 77 columns]

# Make a copy of the Dataset

In [3]:
fd2=fd.copy()

In [4]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   ID                18979 non-null  int64         
 1   Name              18979 non-null  object        
 2   LongName          18979 non-null  object        
 3   photoUrl          18979 non-null  object        
 4   playerUrl         18979 non-null  object        
 5   Nationality       18979 non-null  object        
 6   Age               18979 non-null  int64         
 7   ↓OVA              18979 non-null  int64         
 8   POT               18979 non-null  int64         
 9   Club              18979 non-null  object        
 10  Contract          18979 non-null  object        
 11  Positions         18979 non-null  object        
 12  Height            18979 non-null  object        
 13  Weight            18979 non-null  object        
 14  Preferred Foot    1897

In [5]:
fd.index

RangeIndex(start=0, stop=18979, step=1)

# Checking for missing Values

In [6]:
missing_values_count=fd.isnull().sum()
missing_values_count

ID              0
Name            0
LongName        0
photoUrl        0
playerUrl       0
             ... 
PAS             0
DRI             0
DEF             0
PHY             0
Hits         2595
Length: 77, dtype: int64

In [7]:
Total_missing=missing_values_count.sum()
print(Total_missing)

20561


# Dealing with missing data

In [8]:
fd.drop('Loan Date End', axis=1, inplace=True)
fd['Hits'].fillna(0, inplace=True)

In [9]:
if fd.isnull().values.any():
    print('Null values present')
else:
    print('No Null values')

No Null values


In [10]:
fd.isnull().values.any()

False

In [11]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 76 columns):
 #   Column            Non-Null Count  Dtype         
---  ------            --------------  -----         
 0   ID                18979 non-null  int64         
 1   Name              18979 non-null  object        
 2   LongName          18979 non-null  object        
 3   photoUrl          18979 non-null  object        
 4   playerUrl         18979 non-null  object        
 5   Nationality       18979 non-null  object        
 6   Age               18979 non-null  int64         
 7   ↓OVA              18979 non-null  int64         
 8   POT               18979 non-null  int64         
 9   Club              18979 non-null  object        
 10  Contract          18979 non-null  object        
 11  Positions         18979 non-null  object        
 12  Height            18979 non-null  object        
 13  Weight            18979 non-null  object        
 14  Preferred Foot    1897

In [12]:
fd.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Value', 'Wage',
       'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
 

# Drop columns that may not be needed

In [13]:
fd.drop(['playerUrl'], axis =1, inplace = True)
fd.drop('Name',axis =1, inplace=True)

In [14]:
fd.iloc[:,1:21].head(6)

LongName  \
0                  Lionel Messi   
1  C. Ronaldo dos Santos Aveiro   
2                     Jan Oblak   
3               Kevin De Bruyne   
4    Neymar da Silva Santos Jr.   
5            Robert Lewandowski   

                                           photoUrl Nationality  Age  ↓OVA  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   Argentina   33    93   
1  https://cdn.sofifa.com/players/020/801/21_60.png    Portugal   35    92   
2  https://cdn.sofifa.com/players/200/389/21_60.png    Slovenia   27    91   
3  https://cdn.sofifa.com/players/192/985/21_60.png     Belgium   29    91   
4  https://cdn.sofifa.com/players/190/871/21_60.png      Brazil   28    91   
5  https://cdn.sofifa.com/players/188/545/21_60.png      Poland   31    91   

   POT                         Club     Contract   Positions Height Weight  \
0   93         \n\n\n\nFC Barcelona  2004 ~ 2021  RW, ST, CF  170cm   72kg   
1   92             \n\n\n\nJuventus  2018 ~ 2022      ST, LW  187cm   83kg   
2   93      \n\n\n\nAtlético Madrid  2014 ~ 2023          GK  188cm   87kg   
3   91      \n\n\n\nManchester City  2015 ~ 2023     CAM, CM  181cm   70kg   
4   91  \n\n\n\nParis Saint-Germain  2017 ~ 2022     LW, CAM  175cm   68kg   
5   91    \n\n\n\nFC Bayern München  2014 ~ 2023          ST  184cm   80kg   

  Preferred Foot  BOV Best Position     Joined    Value   Wage Release Clause  \
0           Left   93            RW 2004-07-01  €103.5M  €560K        €138.4M   
1          Right   92            ST 2018-07-10     €63M  €220K         €75.9M   
2          Right   91            GK 2014-07-16    €120M  €125K        €159.4M   
3          Right   91           CAM 2015-08-30    €129M  €370K          €161M   
4          Right   91            LW 2017-08-03    €132M  €270K        €166.5M   
5          Right   91            ST 2014-07-01    €111M  €240K          €132M   

   Attacking  Crossing  
0        429        85  
1        437        84  
2         95        13  
3        407        94  
4        408        85  
5        423        71

# Cleaning the Club column

In [15]:
def clean(column):
    return column[4:]

fd['Club'] = fd['Club'].apply(clean)

In [16]:
fd['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City',
       'Paris Saint-Germain', 'FC Bayern München', 'Liverpool',
       'Real Madrid', 'Chelsea', 'Tottenham Hotspur', 'Inter', 'Napoli',
       'Borussia Dortmund', 'Manchester United', 'Arsenal', 'Lazio',
       'Leicester City', 'Borussia Mönchengladbach', 'Real Sociedad',
       'Atalanta', 'Olympique Lyonnais', 'Milan', 'Villarreal CF',
       'RB Leipzig', 'Cagliari', 'Ajax', 'SL Benfica', 'AS Monaco',
       'Wolverhampton Wanderers', 'Everton', 'Fiorentina', 'FC Porto',
       'RC Celta', 'Torino', 'Sevilla FC', 'Grêmio', 'Real Betis', 'Roma',
       'Newcastle United', 'Eintracht Frankfurt', 'Valencia CF',
       'Medipol Başakşehir FK', 'Inter Miami', 'Bayer 04 Leverkusen',
       'Levante UD', 'Crystal Palace', 'Athletic Club de Bilbao',
       'Shanghai SIPG FC', 'VfL Wolfsburg',
       'Guangzhou Evergrande Taobao FC', 'Al Shabab',
       'Olympique de Marseille', 'Los Angeles FC',
       'Beijing Sino

# Renaming columns more appropraitely 

In [17]:

fd.rename(columns={'↓OVA':'OVA'}, inplace=True)
fd.rename(columns={'LongName':'Full_name'}, inplace=True)

In [18]:
fd.head(1)

ID     Full_name                                          photoUrl  \
0  158023  Lionel Messi  https://cdn.sofifa.com/players/158/023/21_60.png   

  Nationality  Age  OVA  POT          Club     Contract   Positions  ...  \
0   Argentina   33   93   93  FC Barcelona  2004 ~ 2021  RW, ST, CF  ...   

      A/W  D/W   IR  PAC SHO PAS DRI DEF PHY  Hits  
0  Medium  Low  5 ★   85  92  91  95  38  65   771  

[1 rows x 74 columns]

# Checking the contract column

In [19]:
fd['Contract'].unique()

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 

From the contract column, we can see that there are different categories of data. some players are on contract, some players 
are on loan , while some players are neither on loan nor on contract.
I will change it to a categorical data.
If player is on loan it will return "On loan", if on contract it
will return "Contract_Active", if player is not on contract it will return "No contract"

# Work on the contract column & Change column name

In [20]:
def contract(x):
    if 'On Loan' in x:
        return 'On Loan'
    elif'~' in x:
        return 'Contract_active'
    elif 'Free' in x:
        return 'Free'
        

In [21]:
fd['Contract']=fd['Contract'].apply(contract)

In [22]:
fd['Contract'].unique()

array(['Contract_active', 'On Loan', 'Free'], dtype=object)

# Rename the contract column

In [23]:
fd.rename(columns={'Contract':'Contract_status'}, inplace=True)


In [24]:
fd.iloc[:6,1:21]

Full_name  \
0                  Lionel Messi   
1  C. Ronaldo dos Santos Aveiro   
2                     Jan Oblak   
3               Kevin De Bruyne   
4    Neymar da Silva Santos Jr.   
5            Robert Lewandowski   

                                           photoUrl Nationality  Age  OVA  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   Argentina   33   93   
1  https://cdn.sofifa.com/players/020/801/21_60.png    Portugal   35   92   
2  https://cdn.sofifa.com/players/200/389/21_60.png    Slovenia   27   91   
3  https://cdn.sofifa.com/players/192/985/21_60.png     Belgium   29   91   
4  https://cdn.sofifa.com/players/190/871/21_60.png      Brazil   28   91   
5  https://cdn.sofifa.com/players/188/545/21_60.png      Poland   31   91   

   POT                 Club  Contract_status   Positions Height Weight  \
0   93         FC Barcelona  Contract_active  RW, ST, CF  170cm   72kg   
1   92             Juventus  Contract_active      ST, LW  187cm   83kg   
2   93      Atlético Madrid  Contract_active          GK  188cm   87kg   
3   91      Manchester City  Contract_active     CAM, CM  181cm   70kg   
4   91  Paris Saint-Germain  Contract_active     LW, CAM  175cm   68kg   
5   91    FC Bayern München  Contract_active          ST  184cm   80kg   

  Preferred Foot  BOV Best Position     Joined    Value   Wage Release Clause  \
0           Left   93            RW 2004-07-01  €103.5M  €560K        €138.4M   
1          Right   92            ST 2018-07-10     €63M  €220K         €75.9M   
2          Right   91            GK 2014-07-16    €120M  €125K        €159.4M   
3          Right   91           CAM 2015-08-30    €129M  €370K          €161M   
4          Right   91            LW 2017-08-03    €132M  €270K        €166.5M   
5          Right   91            ST 2014-07-01    €111M  €240K          €132M   

   Attacking  Crossing  
0        429        85  
1        437        84  
2         95        13  
3        407        94  
4        408        85  
5        423        71

# cleaning the height and weight columns

In [25]:
fd['Height'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [26]:
def conv_height(x):
    if x[-1]=='"':
        x=x.replace("\"","")
        inch=int(x[2:])*2.54
        foot=int(x[0])*30.48
        return int(foot+inch)
    elif x[-1]=='m':
        return int(x[:-2])
    

In [27]:
fd['Height']=fd['Height'].apply(conv_height)

In [28]:
fd['Height'].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 162,
       201, 158, 161, 160, 203, 157, 156, 202, 159, 206, 155], dtype=int64)

In [29]:
fd['Height'].nunique()

50

In [30]:
def conv_weight(x):
    if x[-1]=='"':
        x=x.replace("\"","")
        inch=int(x[2:])*2.54
        foot=int(x[0])*30.48
        return int(foot+inch)
    elif x[-1]=='m':
        return int(x[:-2])
    

In [31]:
fd.rename(columns={'Height':'Height(cm)'}, inplace= True)

In [32]:
fd.head(1)

ID     Full_name                                          photoUrl  \
0  158023  Lionel Messi  https://cdn.sofifa.com/players/158/023/21_60.png   

  Nationality  Age  OVA  POT          Club  Contract_status   Positions  ...  \
0   Argentina   33   93   93  FC Barcelona  Contract_active  RW, ST, CF  ...   

      A/W  D/W   IR  PAC SHO PAS DRI DEF PHY  Hits  
0  Medium  Low  5 ★   85  92  91  95  38  65   771  

[1 rows x 74 columns]

In [33]:
#fd['Height']=fd['Height'].str.replace('cm','').astype(int)
#fd['Weight']=fd['Weight'].str.replace('kg','').astype(int)



In [34]:
fd['Weight'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [35]:
def conv_weight(y):
    if 'lbs'in y:
        y=y.replace('lbs','')
        y=float(y)*0.453592
        y=int(y)
        return y
    else:
        return int(y[:-2])
    

In [36]:
fd['Weight']=fd['Weight'].apply(conv_weight)

In [37]:
fd['Weight'].unique()

array([ 72,  83,  87,  70,  68,  80,  71,  91,  73,  85,  92,  69,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  93,  88,  97,  77,  62,  63,  95,
       100,  58,  98, 103,  99, 102,  56, 101,  57,  55, 104, 107, 110,
        53,  50,  54,  52], dtype=int64)

In [38]:
fd.rename(columns={'Weight':'Weight(kg)'},inplace=True)

# Checking other columns

In [39]:
#Preferred foot column is okay
fd['Preferred Foot'].unique()

array(['Left', 'Right'], dtype=object)

In [40]:
#BOV, Best Position, Attacking, crossing, Finishing, Head Accuracy, Short Passing, Volleys, Skill columns are okay
fd['BOV'].unique()

array([93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77,
       76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60,
       59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48], dtype=int64)

In [41]:
fd['Best Position'].unique()

array(['RW', 'ST', 'GK', 'CAM', 'LW', 'CB', 'CDM', 'CF', 'CM', 'RB', 'LB',
       'LM', 'RM', 'LWB', 'RWB'], dtype=object)

In [42]:
fd['Attacking'].unique()

array([429, 437,  95, 407, 408, 423, 392, 114, 118, 316, 410, 349,  86,
       119, 426, 374, 411, 360, 328, 383, 405, 123, 420, 224, 388, 397,
       425, 373, 365, 371, 311, 396, 345, 399, 400,  78, 280, 330, 403,
       379, 380,  94, 394, 419, 339, 293, 344, 390,  84, 359, 372, 377,
       346, 389, 386, 308, 277, 382, 368, 402, 292, 298, 366, 352, 363,
       322, 361,  91, 364, 341, 385, 355, 305, 321, 262,  93, 375, 387,
       356, 253, 285, 391, 353, 367,  90, 295, 378, 256, 338, 331,  69,
       105,  85, 358, 343, 319, 271, 113, 350, 406, 340, 393, 247, 334,
       351, 342, 302, 329, 354,  98, 301, 115, 384, 208,  72, 376,  92,
       258, 362,  74, 417,  99, 263,  88, 279, 101, 395, 100,  81,  87,
        55, 310,  82, 117, 409, 318, 323, 248, 315, 381, 348, 327, 309,
       130, 283, 336, 369, 106, 252, 320, 290, 370, 126, 251, 108, 335,
       297, 284,  80,  75, 357, 270,  97, 306, 337,  73, 286, 325, 326,
       324, 333, 103, 259, 273, 313, 296,  61, 312, 347, 401, 30

In [43]:
fd['Finishing'].unique()

array([95, 11, 82, 87, 94, 91, 13, 14, 52, 90, 64, 88, 65, 85, 66, 84, 10,
       22, 76, 81, 56, 79, 57, 45, 77, 63, 86, 80, 15, 33, 67, 12, 72, 92,
       93, 51, 46, 60, 75, 55, 73, 83, 50, 42, 39, 40,  9, 68, 48, 37, 70,
       78, 69,  8, 53, 89, 25, 62, 71, 74, 44, 26, 19, 32, 18, 61, 58, 30,
       54, 36, 29, 16, 38, 59, 27, 34, 47, 20, 31, 49, 43, 41, 28,  5,  7,
        6, 21, 17, 35, 23, 24,  4,  3], dtype=int64)

In [44]:
fd['Volleys'].unique()

array([88, 86, 13, 82, 87, 89, 79, 20, 83, 14, 45, 75, 63, 12, 11, 69, 67,
       56, 18, 85, 62, 70, 32, 40, 47, 81, 44, 84, 78, 76, 90, 49, 42, 64,
       57, 60,  8, 72, 71, 59, 74, 80, 73, 37, 31, 38, 61, 10, 77, 68, 58,
       66, 30, 33, 65, 27, 51, 15, 16, 50, 43, 35, 24, 17, 34, 28,  9, 39,
       52, 46, 22, 19, 53, 55, 48, 54, 23,  5, 41, 25, 21, 36, 26, 29,  6,
        7,  4,  3], dtype=int64)

In [45]:
fd.iloc[:,10:25].head()

Height(cm)  Weight(kg) Preferred Foot  BOV Best Position     Joined  \
0         170          72           Left   93            RW 2004-07-01   
1         187          83          Right   92            ST 2018-07-10   
2         188          87          Right   91            GK 2014-07-16   
3         181          70          Right   91           CAM 2015-08-30   
4         175          68          Right   91            LW 2017-08-03   

     Value   Wage Release Clause  Attacking  Crossing  Finishing  \
0  €103.5M  €560K        €138.4M        429        85         95   
1     €63M  €220K         €75.9M        437        84         95   
2    €120M  €125K        €159.4M         95        13         11   
3    €129M  €370K          €161M        407        94         82   
4    €132M  €270K        €166.5M        408        85         87   

   Heading Accuracy  Short Passing  Volleys  
0                70             91       88  
1                90             82       86  
2                15             43       13  
3                55             94       82  
4                62             87       87

In [46]:
fd.iloc[:,26:40].head(6)

Dribbling  Curve  FK Accuracy  Long Passing  Ball Control  Movement  \
0         96     93           94            91            96       451   
1         88     81           76            77            92       431   
2         12     13           14            40            30       307   
3         88     85           83            93            92       398   
4         95     88           89            81            95       453   
5         85     79           85            70            88       407   

   Acceleration  Sprint Speed  Agility  Reactions  Balance  Power  Shot Power  \
0            91            80       91         94       95    389          86   
1            87            91       87         95       71    444          94   
2            43            60       67         88       49    268          59   
3            77            76       78         91       76    408          91   
4            94            89       96         91       83    357          80   
5            77            78       77         93       82    420          89   

   Jumping  
0       68  
1       95  
2       78  
3       63  
4       62  
5       84

In [47]:
fd.iloc[:,41:].head()

Strength  Long Shots  Mentality  Aggression  Interceptions  Positioning  \
0        69          94        347          44             40           93   
1        78          93        353          63             29           95   
2        78          12        140          34             19           11   
3        74          91        408          76             66           88   
4        50          84        356          51             36           87   

   Vision  Penalties  Composure  Defending  ...     A/W     D/W   IR  PAC  \
0      95         75         96         91  ...  Medium     Low  5 ★   85   
1      82         84         95         84  ...    High     Low  5 ★   89   
2      65         11         68         57  ...  Medium  Medium  3 ★   87   
3      94         84         91        186  ...    High    High  4 ★   76   
4      90         92         93         94  ...    High  Medium  5 ★   91   

   SHO  PAS  DRI  DEF  PHY  Hits  
0   92   91   95   38   65   771  
1   93   81   89   35   77   562  
2   92   78   90   52   90   150  
3   86   93   88   64   78   207  
4   85   86   94   36   59   595  

[5 rows x 33 columns]

In [48]:
fd['A/W'].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [49]:
fd['D/W'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [50]:
fd.iloc[:,41:].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Strength         18979 non-null  int64 
 1   Long Shots       18979 non-null  int64 
 2   Mentality        18979 non-null  int64 
 3   Aggression       18979 non-null  int64 
 4   Interceptions    18979 non-null  int64 
 5   Positioning      18979 non-null  int64 
 6   Vision           18979 non-null  int64 
 7   Penalties        18979 non-null  int64 
 8   Composure        18979 non-null  int64 
 9   Defending        18979 non-null  int64 
 10  Marking          18979 non-null  int64 
 11  Standing Tackle  18979 non-null  int64 
 12  Sliding Tackle   18979 non-null  int64 
 13  Goalkeeping      18979 non-null  int64 
 14  GK Diving        18979 non-null  int64 
 15  GK Handling      18979 non-null  int64 
 16  GK Kicking       18979 non-null  int64 
 17  GK Positioning   18979 non-null

# Let us clean the Value, Wage and Release Clause	

In [51]:
fd['Value']=fd['Value'].str.strip('€')

In [52]:
fd['Value']=fd['Value'].astype(str)

def val(b):
    if 'K' in b:
        b= b.replace('K','')
        b= float(b)
        b=int(b)*1000
        return b
    elif 'M' in b:
        b=b.replace('M','')
        b=float(b)
        b=int(b)*1000000
        return b
    else:
        b=b
        return b
        
fd['Value']=fd['Value'].apply(val)

In [53]:
fd['Value'].head()

0    103000000
1     63000000
2    120000000
3    129000000
4    132000000
Name: Value, dtype: object

In [54]:
fd['Wage']=fd['Wage'].str.strip('€')
fd['Wage']=fd['Wage'].astype(str)
fd['Wage']=fd['Wage'].apply(val)


In [55]:
fd['Release Clause']=fd['Release Clause'].str.strip('€')
fd['Release Clause']=fd['Release Clause'].astype(str)
fd['Release Clause']=fd['Release Clause'].apply(val)

In [56]:
fd['Release Clause'].head()

0    138000000
1     75000000
2    159000000
3    161000000
4    166000000
Name: Release Clause, dtype: object

# Change Value, Wage and Release Clause columns to int datatypes

In [57]:
fd['Release Clause']=pd.to_numeric(fd['Release Clause'], errors='coerce')
#fd['Wage']=fd['Wage'].astype('Int64')
#fd['Value']=fd['Value'].astype('Int64')

In [58]:
fd['Release Clause'].head()

0    138000000.0
1     75000000.0
2    159000000.0
3    161000000.0
4    166000000.0
Name: Release Clause, dtype: float64

In [59]:
fd['Release Clause'].isnull().sum()

1261

In [60]:
fd['Wage'].head()

0    560000
1    220000
2    125000
3    370000
4    270000
Name: Wage, dtype: object

In [61]:
fd['Value'].head()

0    103000000
1     63000000
2    120000000
3    129000000
4    132000000
Name: Value, dtype: object

In [62]:
fd['Wage'].head()

0    560000
1    220000
2    125000
3    370000
4    270000
Name: Wage, dtype: object

In [63]:
fd['Wage']=pd.to_numeric(fd['Wage'], errors='coerce')

In [64]:
fd['Release Clause'].unique()

array([1.38e+08, 7.50e+07, 1.59e+08, 1.61e+08, 1.66e+08, 1.32e+08,
       1.44e+08, 1.20e+08, 2.03e+08, 1.47e+08, 1.45e+08, 1.22e+08,
       1.19e+08, 4.70e+07, 1.08e+08, 5.00e+07, 9.80e+07, 1.39e+08,
       9.60e+07, 1.12e+08, 1.03e+08, 1.40e+08, 2.70e+07, 8.50e+07,
       1.18e+08, 1.15e+08, 1.02e+08, 1.07e+08, 1.24e+08, 1.04e+08,
       9.90e+07, 2.50e+07, 7.70e+07, 5.60e+07, 7.20e+07, 6.40e+07,
       5.10e+07, 8.20e+07, 6.90e+07, 5.90e+07, 5.30e+07, 4.30e+07,
       4.80e+07, 5.80e+07, 6.50e+07, 6.70e+07, 8.40e+07, 8.70e+07,
       9.50e+07, 9.10e+07, 7.90e+07, 1.11e+08, 7.80e+07, 8.10e+07,
       8.80e+07, 8.60e+07, 9.40e+07, 9.70e+07, 6.30e+07, 5.40e+07,
       2.10e+07, 6.60e+07, 5.20e+07, 6.80e+07, 4.40e+07, 2.90e+07,
       4.00e+07, 2.40e+07, 5.70e+07, 7.60e+07, 7.10e+07, 6.10e+07,
       7.30e+07, 7.00e+07, 3.80e+07, 6.20e+07, 4.20e+07, 3.20e+07,
       4.50e+07, 1.70e+07, 4.60e+07, 2.80e+07, 3.60e+07, 3.70e+07,
       2.30e+07, 4.90e+07, 6.00e+07, 5.50e+07, 3.10e+07, 3.50e

In [65]:
fd['Release Clause'].head()

0    138000000.0
1     75000000.0
2    159000000.0
3    161000000.0
4    166000000.0
Name: Release Clause, dtype: float64

In [66]:
fd['Value'].isnull().sum()

0

In [67]:
fd.iloc[:,35:50].head(6)

Reactions  Balance  Power  Shot Power  Jumping  Stamina  Strength  \
0         94       95    389          86       68       72        69   
1         95       71    444          94       95       84        78   
2         88       49    268          59       78       41        78   
3         91       76    408          91       63       89        74   
4         91       83    357          80       62       81        50   
5         93       82    420          89       84       76        86   

   Long Shots  Mentality  Aggression  Interceptions  Positioning  Vision  \
0          94        347          44             40           93      95   
1          93        353          63             29           95      82   
2          12        140          34             19           11      65   
3          91        408          76             66           88      94   
4          84        356          51             36           87      90   
5          85        391          81             49           94      79   

   Penalties  Composure  
0         75         96  
1         84         95  
2         11         68  
3         84         91  
4         92         93  
5         88         88

In [68]:
fd.iloc[:,51:66].head(6)

Marking  Standing Tackle  Sliding Tackle  Goalkeeping  GK Diving  \
0       32               35              24           54          6   
1       28               32              24           58          7   
2       27               12              18          437         87   
3       68               65              53           56         15   
4       35               30              29           59          9   
5       35               42              19           51         15   

   GK Handling  GK Kicking  GK Positioning  GK Reflexes  Total Stats  \
0           11          15              14            8         2231   
1           11          15              14           11         2221   
2           92          78              90           90         1413   
3           13           5              10           13         2304   
4            9          15              15           11         2175   
5            6          12               8           10         2195   

   Base Stats  W/F  SM     A/W     D/W  
0         466  4 ★  4★  Medium     Low  
1         464  4 ★  5★    High     Low  
2         489  3 ★  1★  Medium  Medium  
3         485  5 ★  4★    High    High  
4         451  5 ★  5★    High  Medium  
5         457  4 ★  4★    High  Medium

# Remove star(★) from IR, W/F, SM columns and change datatype to int

In [69]:
fd['IR'].unique()

array(['5 ★', '3 ★', '4 ★', '2 ★', '1 ★'], dtype=object)

In [70]:
def clean_star(x):
    x=x.replace('★','')
    return x

In [71]:
fd['IR']=fd['IR'].apply(clean_star)
fd['W/F']=fd['W/F'].apply(clean_star)
fd['SM']=fd['SM'].apply(clean_star)

In [72]:
fd[['IR','W/F','SM']].head()

IR W/F SM
0  5   4   4
1  5   4   5
2  3   3   1
3  4   5   4
4  5   5   5

In [73]:
#Now convert it using pd.to_numeric()
fd['IR']=pd.to_numeric(fd['IR'])

In [74]:
fd['W/F']=pd.to_numeric(fd['W/F'])
fd['SM']=pd.to_numeric(fd['SM'])

In [75]:
fd[['IR','W/F','SM']].dtypes

IR     int64
W/F    int64
SM     int64
dtype: object

# Let us work on the Hits Column...multiplty the vals having 'k' by 1000, also change data type

In [76]:
fd.Hits.isnull().sum()

0

In [77]:
fd.Hits.unique()

array([771, 562, 150, 207, 595, 248, 246, 120, '1.6K', 130, 321, 189, 175,
       96, 118, 216, 212, 154, 205, 202, 339, 408, 103, 332, 86, 173, 161,
       396, '1.1K', 433, 242, 206, 177, '1.5K', 198, 459, 117, 119, 209,
       84, 187, 165, 203, 65, 336, 126, 313, 124, 145, 538, 182, 101, 45,
       377, 99, 194, 403, 414, 593, 374, 245, '3.2K', 266, 299, 309, 215,
       265, 211, 112, 337, 70, 159, 688, 116, 63, 144, 123, 71, 224, 113,
       168, 61, 89, 137, 278, 75, 148, 176, 197, 264, 214, 247, 402, 440,
       '1.7K', '2.3K', 171, 320, 657, 87, 259, 200, 255, 253, 196, 60, 97,
       85, 169, 256, 132, 239, 166, 121, 109, 32, 46, 122, 48, 527, 199,
       282, 51, '1.9K', 642, 155, 323, 288, 497, 509, 79, 49, 270, 511,
       80, 128, 115, 156, 204, 143, 140, 152, 220, 134, 225, 94, 74, 135,
       142, 50, 77, 40, 107, 193, 179, 34, 64, 453, 57, 81, 28, 78, 133,
       43, 425, 88, 42, 36, 233, 376, 210, 444, 100, 263, 98, 29, 160, 39,
       257, 6, 310, 138, 62, 293, 285, 

In [78]:
fd['Hits']=fd['Hits'].astype(str)

def hitcol(b):
    if 'K' in b:
        b= b.replace('K','')
        b= float(b)
        b=int(b)*1000
        return b
    else:
        b=b
        return b
        

In [79]:
fd['Hits']=fd['Hits'].apply(hitcol)

In [80]:
fd['Hits'].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', 1000,
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '433', '242', '206', '177', '198', '459', '117', '119',
       '209', '84', '187', '165', '203', '65', '336', '126', '313', '124',
       '145', '538', '182', '101', '45', '377', '99', '194', '403', '414',
       '593', '374', '245', 3000, '266', '299', '309', '215', '265',
       '211', '112', '337', '70', '159', '688', '116', '63', '144', '123',
       '71', '224', '113', '168', '61', '89', '137', '278', '75', '148',
       '176', '197', '264', '214', '247', '402', '440', 2000, '171',
       '320', '657', '87', '259', '200', '255', '253', '196', '60', '97',
       '85', '169', '256', '132', '239', '166', '121', '109', '32', '46',
       '122', '48', '527', '199', '282', '51', '642', '155', '323', '288',
       '497', '509', '79', '49', '270', '511', '80', '128', '115

In [81]:
fd['Hits'].dtype

dtype('O')

In [82]:
fd['Hits']=pd.to_numeric(fd['Hits'])

In [83]:
fd['Hits'].isnull().sum()

0

In [84]:
fd['Joined']=pd.to_datetime(fd['Joined'])

# Checking for duplicates

In [85]:
fd[fd.duplicated()]

Empty DataFrame
Columns: [ID, Full_name, photoUrl, Nationality, Age, OVA, POT, Club, Contract_status, Positions, Height(cm), Weight(kg), Preferred Foot, BOV, Best Position, Joined, Value, Wage, Release Clause, Attacking, Crossing, Finishing, Heading Accuracy, Short Passing, Volleys, Skill, Dribbling, Curve, FK Accuracy, Long Passing, Ball Control, Movement, Acceleration, Sprint Speed, Agility, Reactions, Balance, Power, Shot Power, Jumping, Stamina, Strength, Long Shots, Mentality, Aggression, Interceptions, Positioning, Vision, Penalties, Composure, Defending, Marking, Standing Tackle, Sliding Tackle, Goalkeeping, GK Diving, GK Handling, GK Kicking, GK Positioning, GK Reflexes, Total Stats, Base Stats, W/F, SM, A/W, D/W, IR, PAC, SHO, PAS, DRI, DEF, PHY, Hits]
Index: []

[0 rows x 74 columns]

# Creating another copy

In [86]:
Cleaned_Fifa_Data=fd.copy()

In [87]:
Cleaned_Fifa_Data.head(3)

ID                     Full_name  \
0  158023                  Lionel Messi   
1   20801  C. Ronaldo dos Santos Aveiro   
2  200389                     Jan Oblak   

                                           photoUrl Nationality  Age  OVA  \
0  https://cdn.sofifa.com/players/158/023/21_60.png   Argentina   33   93   
1  https://cdn.sofifa.com/players/020/801/21_60.png    Portugal   35   92   
2  https://cdn.sofifa.com/players/200/389/21_60.png    Slovenia   27   91   

   POT             Club  Contract_status   Positions  ...     A/W     D/W IR  \
0   93     FC Barcelona  Contract_active  RW, ST, CF  ...  Medium     Low  5   
1   92         Juventus  Contract_active      ST, LW  ...    High     Low  5   
2   93  Atlético Madrid  Contract_active          GK  ...  Medium  Medium  3   

   PAC SHO PAS DRI  DEF  PHY  Hits  
0   85  92  91  95   38   65   771  
1   89  93  81  89   35   77   562  
2   87  92  78  90   52   90   150  

[3 rows x 74 columns]